server:
  port: 8088
  session:
    timeout: 1800
spring:
  thymeleaf:
    cache: false
  session:  
    #store-type: redis
    store-type: none
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fxs-platform?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    tomcat: 
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 1800000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      naming:
        implicit-strategy: com.fxs.platform.repository.support.FxsImplicitNamingStrategy
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: guava
    guava:
      spec: maximumSize=500,expireAfterWrite=365d
fxs:
  constant:
    city-id: 10101,10102,10122
  security:
    message:
      base-name: classpath:i18n/messages-application
    browser:
      sign-in-page: /user/signIn
      sign-in-response-type: REDIRECT
      sing-in-successUrl: /user/dashboard
      remember-me-seconds: 29400
      sign-out-url: /user/signIn
      ignoring-url: /,/city/**,/case/**,/lawsuit/**,/consultation/**
    #session:
      #maximum-sessions: 1
      #max-sessions-prevents-login: true
      #session-invalid-url: /fxs-session-invalid.html
    #code:
      #image:
        #length: 4
        #width: 100
        #height: 30
        #expire-in: 60
        #url: /user/*
    