server:
  port: 8090
  session:
    timeout: 1800
spring:
  thymeleaf:
    cache: false
  session:  
    #store-type: redis
    store-type: none
  datasource:
    username: root
    password: Root,123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.187.165:3306/fxs-platform?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    tomcat: 
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 1800000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      #naming:
        #implicit-strategy: com.fxs.platform.repository.support.FxsImplicitNamingStrategy
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: guava
    guava:
      spec: maximumSize=500,expireAfterWrite=365d
fxs:
  constant:
    city-id: 10101,10102,10122
  security:
    message:
      base-name: classpath:i18n/messages-application
    browser:
      sign-in-page: /user/signIn
      sign-in-response-type: REDIRECT
      sing-in-successUrl: /
      remember-me-seconds: 29400
      sign-out-url: /user/signIn\
      acces-forbidden-url: /accessForbidden
      ignoring-url: /city/**
      session:
        #maximum-sessions: 1
        #max-sessions-prevents-login: true
        session-invalid-url: /invalid-session
    #code:
      #image:
        #length: 4
        #width: 100
        #height: 30
        #expire-in: 60
        #url: /user/*
      #sms:
        #length: 4
        #width: 100
        #height: 30
        #expire-in: 60
        #url: /user/*